### PR TITLE
Use "oc get --export" instead of deprecated "oc export"

### LINKED ISSUE #82: Replace deprecated oc export command
OCP 3.10 deprecated the `oc export` command, and we should use `oc get --export` now. See https://docs.openshift.com/container-platform/3.11/release_notes/ocp_3_11_release_notes.html.

### LINKED ISSUE #149: Exclude flag does not have an effect when exporting
When using the `export` command, one can supply the `--exclude` flag without errors, but the flag does not have an effect.

The exported resources should not include those targeted by `--exclude`.

### LINKED ISSUE #158: Comparing CronJob resources does not work
Tailor uses `oc export` to get the cluster state. But that command produces very weird output for `CronJob` resources. There is no `kind` field ...

Even more interesting is that `oc get CronJob -oyaml` produces relatively normal output with a `kind` field of value `CronJob`.

Even more reason to switch from the deprecated `export` to `get` and do cleanup of fields/values ourselves ...

FYI @kiwo

### LINKED ISSUE #188: Exporting just one resource does not work properly
When running `tailor -n foo export dc/bar`, all deployments are exported, not just `bar`.

### PR DESCRIPTION
**Pull request by michaelsauter**
Taking inspiration from #94.

FYI @akhilsoman @henrjk 

Closes #82.

Fixes #158.

Fixes #149.

Fixes #188.

### CODE REVIEW

**Comment by michaelsauter** [comment]
I verified that a binary with this PR works against OpenShift 4.2.

**Comment by henrjk** [comment]
It makes a bit uneasy to make this change without more test coverage. On the other hand making this change sooner than later will give us more time to fix any issues that may pop up.

@michaelsauter: are you aiming to merge this in the current state?  

If yes I would take a bit more time for a more thorough review.

**Comment by michaelsauter** [comment]
@henrjk I was planning to add more tests. I just played around with it and tried the changes against 4.2. 

That said, the implementation should stay as-is. Also, I don't expect a lot of additional tests as in the end, this is an implementation detail and the fact that the E2E tests still run shows that it actually works.

**Comment by michaelsauter** [comment]
Rebased and noticed that the export still included incomparable secrets. Fixing that (by running it through the list structure) also fixed #149 and #188.

**Comment by michaelsauter** [comment]
FYI @henrjk I've done some more testing and will merge this now. Test coverage is at 77.7% right now plus E2E tests. The E2E tests also cover the cases which differ between `export` and `get --export` (service token secrets etc.).

**Pull request merged**
