### PR TITLE
Replace deprecated oc export command 

### PR DESCRIPTION
**Pull request by akhilsoman**
fixing #82

### CODE REVIEW

**Comment by michaelsauter** [comment]
@akhilsoman So if I run `oc get -oyaml --export bc`, then I get back a resource of kind `List`. However, we need to get back a template, because the file we write will be used as input for `oc process` when you run e.g. `tailor status`.

**Comment by michaelsauter** [comment]
@akhilsoman Don't change the test files - the change must happen in a way that the test files are not touched, but the tests still work.

**Comment by akhilsoman** [comment]
@michaelsauter I was trying to play around with the test cases to see the differences between a normal list and template semantics. I will revert it in the final PR.

**Comment by akhilsoman** [comment]
Since export is not implemented for list, only for individual objects this approach will not work. Hence closing the PR
(https://github.com/kubernetes/kubernetes/issues/28551#issuecomment-453532504)

**Pull request closed without merging**
