### PR TITLE
Refactor commands

### PR DESCRIPTION
**Pull request by michaelsauter**
- Each command is now in a separate file inside the "commands" package.
- Further, this change addresses the issue of erronous removal patches
  when a path with an array value was ignored.
- Also, it fixes a bug where Tailor would not find any item if both name
  and selector was given (oc returns a single item then instead of a
  list).

### CODE REVIEW

**Comment by michaelsauter** [comment]
@henrjk This might solve your problems with selectors, I realized that oc returns just one item, not a list if the result happens to be just one item ... I circumvent now by asking for a template, and then treating that as a list.

**Comment by michaelsauter** [comment]
@henrjk Thanks a lot for reviewing.

I am using `--as-template` only to circumvent the problem with the list/non-list, and I thought it does not have other side-effects. But I am not completely sure yet, which is why this is marked as WIP. Looks like you already found some unwanted drift, and I'll have to look into that ...

Regarding annotation removal: The behaviour should be the same as before - do you see anything that has changed?

**Comment by henrjk** [comment]
@michaelsauter regarding the annotation removal: I checked that tailor did this also in v0.9.2 and v.0.9.3, so it is not a regression.

But why does tailor remove the annotation when exporting? 

Regarding the drift: this was also identical with versions v0.9.2 and v0.9.3 as noted in https://github.com/opendevstack/tailor/issues/106#issuecomment-480625907

The new elements appear not strictly necessary. Would it be better if tailor would not report these as drift (they were not in the original template defined in https://github.com/BIX-Digital/ods-project-quickstarters/blob/c67140a9ef56cca551b27dfbfad348416285febe/ocp-templates/templates/bc-docker.yml)?

If yes should/can this be addressed somehow, perhaps by filtering some default content?

**Comment by michaelsauter** [comment]
@henrjk Thanks for checking.

Tailor removes annotation on export because the assumption is that annotation are not supposed to be managed via templates. Annotations are a way for systems to add additional info, so usually the value can not be known in advance, or is even of value to the developer. In order to not cause constant drift, Tailor removes the annotations from the template.

Regarding the drift that you see: I agree that Tailor ideally should not detect them as the properties are not necessary. They have been added by OpenShift automatically. Right now, you need to define them in the template. I guess one way forward would be to check for each key that is detected as drift if the value is the "empty value" (e.g. `null`), and in that case simply set the empty value automatically in the template, that way avoiding the drift. What do you think?

Having said that, I think this PR is good to be merged - agreed?

**Comment by michaelsauter** [comment]
Follow-up enhancment is #107.

**Comment by henrjk** [comment]
Overlooked your question regarding agree to merging. Yes I agree.

**Pull request merged**
