### PR TITLE
Adding list of supported object types to readme

### PR DESCRIPTION
**Pull request by stefanlack**

### CODE REVIEW

**Comment by michaelsauter** [comment]
What's the motivation behind this? Did you encounter issues because some type is not supported?

Also, the place in the readme is way to prominent for me. This sounds more like a case for a troubleshooting doc or something like this ... what do you think?

**Comment by stefanlack** [comment]
@michaelsauter it was just meant for improving documentation of tailor. While openshift 3.11 actualy knows round about 22 object types (see https://docs.openshift.com/container-platform/3.11/cli_reference/basic_cli_operations.html#object-types), tailor only can handle a subset of them.

This fact may be easy to rember and well known for a long term opendevstack- and openshift developer, a newby might strugle on this. Or at least, I struggled on this in past.

**Comment by stefanlack** [comment]
> Also, the place in the readme is way to prominent for me. This sounds more like a case for a troubleshooting doc or something like this ... what do you think?

Good point. In my opinion, the documentation fragment can be moved to whatever place that's more appropriate for this.

**Comment by michaelsauter** [comment]
Added in https://github.com/opendevstack/tailor/commit/09169df39d43c0447fd05090ccac024cb399ac86.

**Pull request closed without merging**
